# Generated by Django 5.0.1 on 2024-01-19 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_crazy_eh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crazy',
            name='owner',
        ),
    ]
