# Generated by Django 5.0.1 on 2024-01-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-profile-pic.jpg', upload_to='profile_pics'),
        ),
    ]
