# Generated by Django 5.0.1 on 2024-01-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='title',
        ),
    ]
