# Generated by Django 5.0.1 on 2024-01-17 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_question_answer_answer'),
        ('users', '0006_remove_answer_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
